name: Update Contributors List

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README with contributors
        uses: rsbondi/contributors-readme-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          readme_path: README.md
          image_size: 100
          columns_per_row: 6
          commit_message: "docs: update contributors"
